# Generated by Django 5.0.4 on 2024-04-14 18:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_task_pomodorosession"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="task",
            name="status",
        ),
        migrations.RemoveField(
            model_name="task",
            name="updated_at",
        ),
    ]
